baseurl = "http://mlworks.cn"
languageCode = "zh_CN"
title = "ML works"
disqusShortname = "mlworks"

[params]
    sidebartitle = "Ryan Zhao"
    sidebartagline = "My thoughts on Machine Learning, Data Mining and Programming."
    bdtjid = "b8bc30deb19cf10a8529f1da3ea7e04c"
